### ISSUE TITLE
抽屉被虚拟键遮挡

### ISSUE THREAD

**Issue by VersusClyne** [cfan8/TGFC#1]
如图：4.4系统
![screenshot_2015-02-09-21-41-10](https://cloud.githubusercontent.com/assets/2111377/6107294/6fb24922-b0a4-11e4-9d24-d716a363738d.png)

**Comment by beterhans** [comment]
同样问题
    On 2/9/15 9:42 PM, VersusClyne wrote:
    
    
      如图：4.4系统
        
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by cfan8** [comment]
刚才做了一个很ugly的workaround，强行把设置改大一点点，就不会被完全遮挡了 
明天应该会有推送

//找了一下，没有找到检测虚拟键的API，都是一些很tricky的hack做法，看着不靠谱就没用了

**Comment by cfan8** [comment]
试了一下感觉挺丑的，目前是侧栏恢复原状，在菜单中增加一个设置的选项

**Comment by 01046** [comment]
哈哈哈哈，真的是改大就绝了

**Comment by jerouy** [comment]
![zzz](https://cloud.githubusercontent.com/assets/8316523/6385731/70a88e60-bdc2-11e4-9065-2c9fdd362e69.jpg)
最底下的“引用”按钮也会这样。
是不是加个全屏模式就好了？

**Comment by cfan8** [comment]
新版本中已经增加“虚拟键优化”选项，虚拟键机型打开此选项即可。已经上传到市场，预计很快就会推送。
